import Head from 'next/head'
import Post from '../Components/Posts/Post'
import PostForm from '../Components/PostForm/PostForm'


import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta 
          name="description"
          content="Generated by create next app" />
        <link 
          rel="icon" 
          href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1 className={styles.title}>
        My Posts
       </h1>

       <ul className={styles.posts}>
          <li>
            <Post 
              content='hey i am a new post on the phone right now' 
              time='2/22/2022'/>
          </li>

          <li>
            <Post 
              content='hey i am a new post' 
              time='2/26/2022'/>
          </li>

          <li>
            <Post
              content='hey i am a new post' 
              time='2/30/2022'/>
          </li>
       </ul>

       <PostForm/>


      </main>

 
    </div>
  )
}
