import Head from 'next/head'
import Post from '../Components/Posts/Post'

import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1 className={styles.title}>
        My Posts
       </h1>

       <ul className={styles.posts}>
          <li>
              <Post 
              content='hey i am a new post on the phone right now' 
              time='222'/>
          </li>

          <li>
          <Post 
          content='hey i am a new post' 
          time='222'/>
          </li>

          <li>
          <Post
           content='hey i am a new post' 
           time='222'/>
          </li>
       </ul>

       <form>
        <textarea className={styles.formContent}></textarea>
        <button className={styles.formButton}>Add New Tweet</button>
       </form>
      </main>

 
    </div>
  )
}
